# Generated by Django 4.2.2 on 2026-02-20 10:17

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_cartorder_saved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorderproducts',
            options={'verbose_name_plural': 'Cart Items'},
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('process', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='processing', max_length=30),
        ),
        migrations.AlterField(
            model_name='cartorderproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=99999999999999),
        ),
        migrations.AlterField(
            model_name='cartorderproducts',
            name='total',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=99999999999999),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='Fresh jpg', upload_to=core.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=12),
        ),
    ]
